repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: detect-aws-credentials
    -   id: detect-private-key
-   repo: https://github.com/psf/black
    rev: '26.1.0'
    hooks:
    -   id: black
        args: [--config=pyproject.toml]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
    - id: mypy
      args: [--ignore-missing-imports, --warn-no-return, --warn-redundant-casts, --disallow-incomplete-defs, --no-namespace-packages ]
-   repo: https://github.com/PyCQA/flake8
    rev: '7.3.0'
    hooks:
    -   id: flake8
        additional_dependencies: [
                'flake8-bugbear==25.11.29',
                'flake8-coding==1.3.2',
                'flake8-comprehensions==3.17.0',
                'flake8-debugger==4.1.2',
                'flake8-deprecated==2.3.0',
                'flake8-docstrings==1.7.0',
                'flake8-isort==7.0.0',
                'flake8-pep3101==2.1.0',
                'flake8-polyfill==1.0.2',
                'flake8-print==5.0.0',
                'flake8-quotes==3.4.0',
                'flake8-string-format==0.3.0',
        ]
